name: Build and deploy container app to Azure Web App - discordBotLokale

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/huw02/discordbot:latest

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # ✅ kræves for OIDC login til Azure
      contents: read
    needs: build

    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B35070C95B714963BB7DB10FCB2612BA }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2237320751384A1588946CB38A04E1CB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCA1161EB1C049BEAD710241007D5210 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'discordBotLokale'
        slot-name: 'Production'
        images: 'ghcr.io/huw02/discordbot:latest'


